### ISSUE TITLE
Support conditions on regular dimensions

### ISSUE THREAD

**Issue by PatrickGannon** [PlasticLizard/Cubicle#1]
This would enable creating dimensions on fields of embedded objects
eg.
dimension :nested_date, :field_name=>"nested_doc.nested_date"

**Comment by PatrickGannon** [comment]
To clarify, the above syntax is supproted, but will fail if "nested_doc" doesn't exist, or if "nested_doc.nested_date" is nil

**Comment by PlasticLizard** [comment]
Implemented in 0.1.6
