### ISSUE TITLE
Would be nice to be able to include dimensions in measure conditions

### ISSUE THREAD

**Issue by PatrickGannon** [PlasticLizard/Cubicle#3]
I would like to be able to filter on a cubicle dimension within a measure's condition.  A convenient way to accomplish this would be for cubicle to check for '${dimension_name}' within a measure condition prior to executing the query, and then substitute that for the underlying javascript definition of the dimension.  For example, if I have a dimension as follows:

elapsed :expiration_age, :expiration_date, :condition=>"this.resolution == 'Pending'",:prefix=>"timeline"

I would like to be able to filter by that in a measure as follows:

count :expired, :field_name=>:id, :condition=>"$expiration_age > 0"

**Comment by PlasticLizard** [comment]
Added this functionality via the Mustache template library. In the example above, you would do this:

elapsed :expiration_age, :expiration_date, :condition=>"this.resolution=='Pending'"
count :expired, :field_name=>:id, :condition=>"{{expiration_age}} > 0"
